default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  url: <%= ENV['DATABASE_URL'] %>

development:
  <<: *default
  database: <%= ENV.fetch("DB_NAME_DEVELOPMENT", "my_local_db") %>

test:
  <<: *default
  database: <%= ENV.fetch("DB_NAME_TEST", "my_test_db") %>

production:
  <<: *default

  # Add cable connection to fix error with solid_cable or Action Cable
  cable:
    <<: *default
    url: <%= ENV['DATABASE_URL'] %>
