default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  url: <%= ENV['DATABASE_URL'] %> # <- this line is key

development:
  <<: *default
  database: <%= ENV.fetch("DB_NAME_DEVELOPMENT", "my_local_db") %>

test:
  <<: *default
  database: <%= ENV.fetch("DB_NAME_TEST", "my_test_db") %>

production:
  <<: *default
